<?php
function remember_menu() {
  $items = array();
  $items['share'] = array(
    'page callback' => 'remember_register_redirect',
    'page arguments' => array('share'),
    'access callback' => TRUE,
  );
  return $items;
};  
  
function remember_register_redirect($name) {
  global $user;

  switch ($name) {
    case 'share':
      if (!$user->uid) {
      	$redirect_path = 'user/register';
      	/*if ($redirect_path == 'user/register') {
      		drupal_set_message(t('Are you ready to start blogging? First you will have to register. If you already have an account, you may simply ' .  l('log in', 'user/login') . '.'));
				}*/
      	/*if ($redirect_path == 'user' || $redirect_path == 'user/login') {
          $url_suffix = 'destination=create/blog';
				}*/
        drupal_goto($redirect_path, $url_suffix);
      }
      else {
        drupal_goto('user/'.$user->uid);
      }
      break;
  }
};

function remember_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['#theme'] = 'user_register';
  $form['actions']['submit']['#value'] = 'Share your story';
  $form['account']['name']['#title'] = 'Your full name';
  $form['account']['name']['#description'] = 'Please enter your full name';
  $form['field_photos']['und']['#description'] = 'Upload up to three photos below.  You may upload video once your story has been created.';
}

function remember_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['#theme'] = 'user_profile_form';
  $form['account']['name']['#title'] = 'Your full name';
  $form['account']['name']['#description'] = 'Please enter your full name';
  $form['actions']['submit']['#value'] = 'Update your story';
}